name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://github.com/elixir-lang/elixir/releases
        elixir: ["1.10.4", "1.9.4", "1.8.2"]
        # http://erlang.org/download/otp_versions_tree.html
        erlang: ["20.3.8", "21.3.8", "22.3.4"]
        ubuntu: ["focal-20200423"]
        include:
          - elixir: "1.10.4"
            erlang: "23.0"
            ubuntu: "focal-20200423"
        exclude:
          - elixir: "1.10.4"
            erlang: "20.3.8"

    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.erlang }}-ubuntu-${{ matrix.ubuntu }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |-
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Check format
      run: mix format --check-formatted

    - name: Run tests
      run: mix test